name: weather-forecast-bot

on:
    schedule:
        - cron: '0 21 * * *'
    workflow_dispatch:

jobs:
    send-weather:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run the bot
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
                FIRST_LOCATE: ${{ secrets.FIRST_LOCATE }}
                SECOND_LOCATE: ${{ secrets.SECOND_LOCATE }}
                FIRST_LOCATE_LATITUDE: ${{ secrets.FIRST_LOCATE_LATITUDE }}
                FIRST_LOCATE_LONGITUDE: ${{ secrets.FIRST_LOCATE_LONGITUDE }}
                SECOND_LOCATE_LATITUDE: ${{ secrets.SECOND_LOCATE_LATITUDE }}
                SECOND_LOCATE_LONGITUDE: ${{ secrets.SECOND_LOCATE_LONGITUDE }}
              run: python main.py