name: weather-forecast-bot

on:
    schedule:
        - cron: '0 21 * * *'
    workflow_dispatch:

jobs:
    send-weather:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run the bot
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
                TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
                CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
                first_locate: ${{ secrets.FIRST_LOCATE }}
                second_locate: ${{ secrets.SECOND_LOCATE }}
                first_locate_lat: ${{ secrets.FIRST_LOCATE_LATITUDE }}
                first_locate_lon: ${{ secrets.FIRST_LOCATE_LONGITUDE }}
                second_locate_lat: ${{ secrets.SECOND_LOCATE_LATITUDE }}
                second_locate_lon: ${{ secrets.SECOND_LOCATE_LONGITUDE }}
              run: python main.py